apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - image: ubuntu:20.04
    command:
      - tail
      - -f
      - /etc/passwd
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
